name:                pun-lang
version:             0.1.0.0
github:              "jtkristensen/pun-lang"
license:             BSD3
author:              "Joachim Tilsted Kristensen"
maintainer:          "joachkr@ifi.uio.no"
copyright:           "2023 Joachim Tilsted Kristensen"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/jtkristensen/pun-lang#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- parsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src

executables:
  pun-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pun-lang

tests:
  pun-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pun-lang
    - tasty
