name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4

# build-and-test:
#   runs-on: ubuntu-latest
#   steps:
#     - name: 'Check out repository'
#       uses: actions/checkout@v3

#     - name: 'Set up stack'
#       uses: haskell/actions/setup@v1.1
#       with:
#         ghc-version:   '9.4.5'
#         enable-stack:  true
#         stack-version: '2.11.1'

#     - name: 'Build with --pedantic'
#       run: stack build --pedantic

#     - name: 'Run tests with --pedantic'
#       run: stack test --pedantic
